name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  pipeline:
    uses: Ashmoret021/Gitops/.github/workflows/main.yml@main
    with:
      TAG: "1.0.0"
    secrets: inherit
    
